"""admin added to user model

Revision ID: 1e61b4bf1fd7
Revises: dbcfcf7f34c6
Create Date: 2019-05-15 13:22:09.551511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e61b4bf1fd7'
down_revision = 'dbcfcf7f34c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
