"""added topic_type to posts

Revision ID: 41f807cb23b7
Revises: 1e61b4bf1fd7
Create Date: 2019-05-15 18:24:10.605508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f807cb23b7'
down_revision = '1e61b4bf1fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('topic_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'topic_type')
    # ### end Alembic commands ###
