"""new fields in user model

Revision ID: 667f5fee3bb7
Revises: d2b5eba5633b
Create Date: 2019-05-04 10:49:47.833328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667f5fee3bb7'
down_revision = 'd2b5eba5633b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
